# -*- coding: utf-8 -*-
"""Assignment No.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOjesOg0kh1hsiz1PFLv05gfix6R_QlB
"""

# Assignment no.1
#set
#list
#tuple
#dict.

# set is the collection of unordered datatypes
#Example given below

myset={"chhaya",11,"BMIT","False",34.55}
print(myset)
myset.add("Anjali")
print(myset)

#list is the collection of diff.database
#example given below

list1=[11,45,"true","name",22.22,"hello"]
print(list1)
print(len(list1))
print(type(list1))

#tuple is the ordered collection of datatypes
#Example given below

mytuple=("chhaya",11,"BMIT","false",43.5)
print(mytuple)
print(len(mytulple))
print(type(mytuple))

#dictionar is the key pair
#Example given below

mydic={
    "NAME":"Anjali",
    "College Name":"BMIT",
    "Class":"S.Y",
    "Branch":"CSE"
    
}
print(mydic)

